apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: ingress-apisix
  labels:
    app.kubernetes.io/name: apisix-etcd
    app.kubernetes.io/instance: apisix
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix-etcd
      app.kubernetes.io/instance: apisix
  serviceName: etcd-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apisix-etcd
        app.kubernetes.io/instance: apisix
      annotations:
        checksum/token-secret: 78004222c985cd66451615cc031f43d159f6d410c1b42be3b3bb332e86b30553
    spec:
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: apisix-etcd
                    app.kubernetes.io/instance: apisix
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      serviceAccountName: "default"
      containers:
        - name: etcd
          image: docker.io/bitnami/etcd:3.5.7-debian-11-r14
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_STS_NAME
              value: "etcd"
            - name: ETCDCTL_API
              value: "3"
            - name: ETCD_ON_K8S
              value: "yes"
            - name: ETCD_START_FROM_SNAPSHOT
              value: "no"
            - name: ETCD_DISASTER_RECOVERY
              value: "no"
            - name: ETCD_NAME
              value: "$(MY_POD_NAME)"
            - name: ETCD_DATA_DIR
              value: "/bitnami/etcd/data"
            - name: ETCD_LOG_LEVEL
              value: "info"
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_AUTH_TOKEN
              value: "jwt,priv-key=/opt/bitnami/etcd/certs/token/jwt-token.pem,sign-method=RS256,ttl=10m"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "https://$(MY_POD_NAME).etcd-headless.ingress-apisix.svc.cluster.local:2379"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "https://0.0.0.0:2379"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "https://$(MY_POD_NAME).etcd-headless.ingress-apisix.svc.cluster.local:2380"
            - name: ETCD_LISTEN_PEER_URLS
              value: "https://0.0.0.0:2380"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "etcd-cluster-k8s"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
            - name: ETCD_INITIAL_CLUSTER
              value: "etcd-0=https://etcd-0.etcd-headless.ingress-apisix.svc.cluster.local:2380,etcd-1=https://etcd-1.etcd-headless.ingress-apisix.svc.cluster.local:2380,etcd-2=https://etcd-2.etcd-headless.ingress-apisix.svc.cluster.local:2380"
            - name: ETCD_CLUSTER_DOMAIN
              value: "etcd-headless.ingress-apisix.svc.cluster.local"
            - name: ETCD_CERT_FILE
              value: "/opt/bitnami/etcd/certs/etcd.pem"
            - name: ETCD_KEY_FILE
              value: "/opt/bitnami/etcd/certs/etcd-key.pem"
            - name: ETCD_CLIENT_CERT_AUTH
              value: "true"
            - name: ETCD_TRUSTED_CA_FILE
              value: "/opt/bitnami/etcd/certs/ca.pem"
            - name: ETCD_PEER_CERT_FILE
              value: "/opt/bitnami/etcd/certs/etcd.pem"
            - name: ETCD_PEER_KEY_FILE
              value: "/opt/bitnami/etcd/certs/etcd-key.pem"
            - name: ETCD_PEER_CLIENT_CERT_AUTH
              value: "true"
            - name: ETCD_PEER_TRUSTED_CA_FILE
              value: "/opt/bitnami/etcd/certs/ca.pem"
          envFrom:
          ports:
            - name: client
              containerPort: 2379
              protocol: TCP
            - name: peer
              containerPort: 2380
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/etcd/healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - /opt/bitnami/scripts/etcd/healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/bitnami/scripts/etcd/prestop.sh
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/etcd
            - name: etcd-jwt-token
              mountPath: /opt/bitnami/etcd/certs/token/
              readOnly: true
            - name: etcd-tls
              mountPath: /opt/bitnami/etcd/certs/
      volumes:
        - name: etcd-jwt-token
          secret:
            secretName: apisix-etcd-jwt-token
            defaultMode: 256
        - configMap:
            name: etcd-tls-config
          name: etcd-tls
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
