---
# Source: apisix-ingress-controller/templates/service-apisix.yaml
apiVersion: v1
kind: Service
metadata:
  name: apisix-ingress-controller-apisix-gateway
  namespace: ingress-apisix
  annotations:
  labels:
    
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/instance: apisix-ingress-controller
    app.kubernetes.io/version: "1.8.0"
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443
  selector:
    
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/instance: apisix-ingress-controller
  type: NodePort # LoadBalancer or NodePort
  externalTrafficPolicy: Cluster
