apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: add-header
spec:
  plugins:
  - name: proxy-rewrite
    enable: true
    config:
      headers: {
        "add": {
          "Content-Security-Policy": "script-src 'self' 'unsafe-inline' 'unsafe-eval'; object-src 'none'; frame-ancestors 'self'",
          "X-XSS-Protection": "1; mode=block",
          "X-Frame-Options": "DENY",
          "Cache-Control": "no-cache",
          "Pragma": "no-cache",
          "X-Content-Type-Options": "nosniff"
        }
      }