---
# Source: apisix/charts/etcd/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: apisix-etcd-headless
  namespace: ingress-apisix
  labels:
    app.kubernetes.io/name: apisix-etcd
    app.kubernetes.io/instance: apisix
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
  selector:
    app.kubernetes.io/name: apisix-etcd
    app.kubernetes.io/instance: apisix
