---
# Source: apisix/charts/etcd/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: ingress-apisix
  labels:
    app.kubernetes.io/name: apisix-etcd
    app.kubernetes.io/instance: apisix
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: "client"
      port: 2379
      targetPort: client
      nodePort: null
    - name: "peer"
      port: 2380
      targetPort: peer
      nodePort: null
  selector:
    app.kubernetes.io/name: apisix-etcd
    app.kubernetes.io/instance: apisix
